import type { Metadata } from "next";
import StoreProvider from "../lib/StoreProvider";
import localFont from "next/font/local";
import "./globals.scss";

const Poppins = localFont({
  src: [
    {
      path: "../../public/Poppins/Poppins-SemiBold.ttf",
      weight: "600",
      style: "SemiBold",
    },
    {
      path: "../../public/Poppins/Poppins-Regular.ttf",
      weight: "400",
      style: "Regular",
    },
    {
      path: "../../public/Poppins/Poppins-Medium.ttf",
      weight: "500",
      style: "Medium",
    },
  ],
});

const Inter = localFont({
  src: [
    {
      path: "../../public/Inter/static/Inter_24pt-Regular.ttf",
      weight: "500",
      style: "Regular",
    },
  ],
});

const PublicSans = localFont({
  src: [
    {
      path: "../../public/Public_Sans/static/PublicSans-SemiBold.ttf",
      weight: "600",
      style: "SemiBold",
    },
  ],
});

const Outfit = localFont({
  src: [
    {
      path: "../../public/Outfit/static/Outfit-SemiBold.ttf",
      weight: "600",
      style: "SemiBold",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Poppins.className} ${Inter.className} ${PublicSans.className} ${Outfit.className}`}
      >
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
